apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-demo-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-demo-customer
  template:
    metadata:
      labels:
        app: ms-demo-customer
    spec:
      containers:
      - name: ms-demo-customer
        image: myacr.azurecr.io/ms-demo-customer:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"        
---
apiVersion: v1
kind: Service
metadata:
  name: hola-mundo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hola-mundo