apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-demo-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-demo-customer
  template:
    metadata:
      labels:
        app: ms-demo-customer
    spec:
      containers:
      - name: ms-demo-customer
        image: #ACR_NAME.azurecr.io/ms-demo-customer:#COMMIT_SHORT_SHA
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "256m"        
        livenessProbe:
          httpGet:
            path: /actuator/health  # Ruta para verificar el estado de la aplicación
            port: 8080
          initialDelaySeconds: 10  # Tiempo de espera antes de iniciar la verificación
          periodSeconds: 5         # Intervalo entre verificaciones
          failureThreshold: 3      # Número de fallos permitidos antes de reiniciar
        readinessProbe:
          httpGet:
            path: /actuator/health    # Ruta para verificar si la aplicación está lista
            port: 8080
          initialDelaySeconds: 5   # Tiempo de espera antes de iniciar la verificación
          periodSeconds: 5        # Intervalo entre verificaciones
          failureThreshold: 3     # Número de fallos permitidos antes de marcar como no listo
---
apiVersion: v1
kind: Service
metadata:
  name: ms-demo-customer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ms-demo-customer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-demo-customer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-demo-customer
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 110Mi    #Valor promedio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-demo-customer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-demo-customer
                port:
                  number: 80
