name: CI/CD Pipeline for AKS

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: "prd-devops-resourcegroup"
  AKS_CLUSTER_NAME: "devops-k8s-01"
  ACR_NAME: "alicorpdevops"
  APP_NAME: "ms-demo-customer"
  IMAGE_TAG: "latest"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Listar
      run: |
        ls -l
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker image to ACR
      run: |
        az acr build --registry ${{ env.ACR_NAME }} --image ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} .
    
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}
    
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s.yaml