name: CI/CD Pipeline for AKS

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: "prd-devops-resourcegroup"
  AKS_CLUSTER_NAME: "devops-k8s-01"
  ACR_NAME: "alicorpdevops"
  APP_NAME: "ms-demo-customer"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Get short commit SHA
      id: commit_sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker image to ACR
      run: |
        az acr build --registry ${{ env.ACR_NAME }} --image ${{ env.APP_NAME }}:${{ env.SHORT_SHA }} .

    - name: Update k8s-deployment.yaml with commit short SHA
      run: |
        sed -i "s|#COMMIT_SHORT_SHA|${{ env.SHORT_SHA }}|" k8s-deployment.yaml
        sed -i "s|#ACR_NAME|${{ env.ACR_NAME }}|" k8s-deployment.yaml

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}
    
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s.yaml
